[build]
    command = "npm run build"
    publish = "dist"

[[headers]]
    for = "*.js"
    [headers.values]
        Cache-Control = "public, max-age=604800"

[[headers]]
    for = "*.css"
    [headers.values]
        Cache-Control = "public, max-age=604800"

[[headers]]
    for = "*.ttf"
    [headers.values]
        Cache-Control = "public, max-age=604800"
